### ISSUE TITLE
Actionable & priority notifications

### ISSUE THREAD

**Issue by freekeys** [home-assistant/home-assistant-android#215]
Thanks for the amazing work on this!

I'm not sure if android has these available like iOS, but it would be brilliant if we could have actionable notifications. And then lower priority for me but still useful would be the critical ones that override do not disturb like the iOS app has.

Thanks again, really appreciate your work on this!

**Comment by allanpersson** [comment]
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/162 ?

**Comment by CodeFinder2** [comment]
I am also interested in having the ability to update and/or remove an existing notification.

And I guess, this is not possible at the moment, correct? :see_no_evil:

**Comment by JBassett** [comment]
Fixed via https://github.com/home-assistant/home-assistant-android/pull/332

**Comment by CodeFinder2** [comment]
@JBassett Thanks, highly appreciated! :-)

Does this already include the [last 3 keyoints](https://github.com/home-assistant/home-assistant-android/issues/215#issuecomment-574632646)? If not, I would propose to let this issue remain open until it's included completely. 😎

**Comment by JBassett** [comment]
I would create another feature enhancement request for the updating/removal.  We support the rest now.  Except icons, and I don't think we plan to support using a custom icon..

**Comment by andriej** [comment]
Would it be possible to add 'custom icon' as a message parameter, just as it is in HTML5?
It's nice differentiation of notification when you can see small image of the category (I use it for lock and other sensors like leak etc.)
